version: '3'
services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '22:22'
      - '81:80'
    volumes:
      - ./iptables.rules:/etc/iptables.rules
    cap_add:
      - NET_ADMIN
    tty: true
